<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="physics">

<!-- Константы: цвета-->
<material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

<!-- Константы: параметры квадрокоптера -->
<xacro:property name="base_width" value="0.2"/>
<xacro:property name="base_length" value="0.7"/>
<xacro:property name="base_high" value="0.1"/>

<xacro:property name="xyz_base_link" value="0 0 0"/>

<xacro:property name="propeller_width" value="0.05"/>
<xacro:property name="propeller_length" value="0.6"/>
<xacro:property name="propeller_high" value="0.01"/>

<xacro:property name="width_wheel" value="0.08"/>
<xacro:property name="radius_wheel" value="0.1"/>

<!-- Реализация класса: Крыло-->
<xacro:macro name="wing" params="prefix rpy size">
  <link name="wing_${prefix}">
    <visual>
    <origin rpy="${rpy}" />
        <geometry>
            <box size="${size}"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
        <geometry>
            <box size="${size}"/>
        </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
</xacro:macro>

<!-- Реализация класса: Крепёж крыла -->
<xacro:macro name="wing_to_base" params="prefix xyz">
  <joint name="wing_${prefix}_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wing_${prefix}"/>
    <origin xyz="${xyz}"/>
  </joint>
</xacro:macro> 
 
<!-- Реализация класса: Пропеллер -->
<xacro:macro name="propeller" params="prefix rpy size">
  <link name="propeller_${prefix}">
    <visual>
    <origin rpy="${rpy}"/>
        <geometry>
            <box size="${size}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <box size="${size}"/>
        </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
</xacro:macro> 

<!-- Реализация класса: Крепёж пропеллера -->
<xacro:macro name="propeller_to_wing" params="prefix xyz">
  <joint name="propeller_${prefix}_joint" type="continuous">
    <parent link="wing_${prefix}"/>
    <child link="propeller_${prefix}"/>
    <origin xyz="${xyz}"/>
    <axis xyz="0 0 1"/>
  </joint>
</xacro:macro> 

<!-- Реализация класса: Колесо -->
<xacro:macro name="wheel" params="prefix length radius">
  <link name="wheel_${prefix}">
    <visual>
       <origin rpy="0 ${3.14/2} 0"/>
       <geometry>
           <cylinder length="${length}" radius="${radius}"/>
       </geometry>
       <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${length}" radius="${radius}"/>
        </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
</xacro:macro> 

<!-- Реализация класса: Крепёж Колеса -->
<xacro:macro name="wheel_to_wing" params="prefix xyz">
  <joint name="wheel_${prefix}_joint" type="continuous">
    <parent link="wing_${prefix}"/>
    <child link="wheel_${prefix}"/>
    <origin xyz="${xyz}"/>
    <axis xyz="0 0 1"/>
  </joint>
</xacro:macro> 

<!-- Создание объекта: Основание -->
<link name="base_link">
  <visual>
  <origin rpy="0 0 0" xyz="${xyz_base_link}"/>
     <geometry>
        <box size="${base_width} ${base_length} ${base_high}"/>
      </geometry>
      <material name="white"/>
  </visual>
  <collision>
      <geometry>
        <box size="${base_width} ${base_length} ${base_high}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
</link>

<!-- Создание объектов и их свойств: Крыло  -->
<xacro:wing prefix="forward_right" rpy="0 0 ${3.14/4}" size="${base_width} ${base_length} ${base_high}"/>
<xacro:wing prefix="forward_left" rpy="0 0 ${7*3.14/4}" size="${base_width} ${base_length} ${base_high}"/>
<xacro:wing prefix="backward_right" rpy="0 0 ${3*3.14/4}" size="${base_width} ${base_length} ${base_high}"/>
<xacro:wing prefix="backward_left" rpy="0 0 ${5*3.14/4}" size="${base_width} ${base_length} ${base_high}"/>

<xacro:wing_to_base prefix="forward_right" xyz="${-base_width} ${base_length/2} 0"/>
<xacro:wing_to_base prefix="forward_left" xyz="${base_width} ${base_length/2} 0"/>
<xacro:wing_to_base prefix="backward_right" xyz="${-base_width} ${-base_length/2} 0"/>
<xacro:wing_to_base prefix="backward_left" xyz="${base_width} ${-base_length/2} 0"/>

<!-- Создание объектов и их свойств: Пропеллер  -->
<xacro:propeller prefix="forward_right" rpy="0 ${3.14/6} 0" size="${propeller_width} ${propeller_length} ${propeller_high}"/>
<xacro:propeller prefix="forward_left" rpy="0 ${5*3.14/6} 0" size="${propeller_width} ${propeller_length} ${propeller_high}"/>
<xacro:propeller prefix="backward_right" rpy="0 ${3.14/6} 0" size="${propeller_width} ${propeller_length} ${propeller_high}"/>
<xacro:propeller prefix="backward_left" rpy="0 ${5*3.14/6} 0" size="${propeller_width} ${propeller_length} ${propeller_high}"/>

<xacro:propeller_to_wing prefix="forward_right" xyz="${-base_width} ${base_length/4} ${base_high/2}"/>
<xacro:propeller_to_wing prefix="forward_left" xyz="${base_width} ${base_length/4} ${base_high/2}"/>
<xacro:propeller_to_wing prefix="backward_right" xyz="${-base_width} ${-base_length/4} ${base_high/2}"/>
<xacro:propeller_to_wing prefix="backward_left" xyz="${base_width} ${-base_length/4} ${base_high/2}"/>

<!-- Создание объектов и их свойств: Колесо  -->
<xacro:wheel prefix="forward_right" length="${width_wheel}" radius="${radius_wheel}"/>
<xacro:wheel prefix="forward_left" length="${width_wheel}" radius="${radius_wheel}"/>
<xacro:wheel prefix="backward_right" length="${width_wheel}" radius="${radius_wheel}"/>
<xacro:wheel prefix="backward_left" length="${width_wheel}" radius="${radius_wheel}"/>

<xacro:wheel_to_wing prefix="forward_right" xyz="${-base_width} ${base_length/4} ${-0.02 +(-base_high/2)}"/>
<xacro:wheel_to_wing prefix="forward_left" xyz="${base_width} ${base_length/4} ${-0.02 +(-base_high/2)}"/>
<xacro:wheel_to_wing prefix="backward_right" xyz="${-base_width} ${-base_length/4} ${-0.02 +(-base_high/2)}"/>
<xacro:wheel_to_wing prefix="backward_left" xyz="${base_width} ${-base_length/4} ${-0.02 +(-base_high/2)}"/>

</robot>









